# Generated by Django 4.0.5 on 2022-06-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='users_list',
            field=models.ManyToManyField(related_name='lists', to='app.user'),
        ),
    ]
