# Generated by Django 4.0.5 on 2022-06-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_movie_users_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='pic',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
