# Generated by Django 2.2.4 on 2021-04-29 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_wish_wish_granted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish_granted',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes_granted', to='app_one.User'),
        ),
    ]
