# Generated by Django 2.2.4 on 2022-06-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('black_belt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='done',
        ),
    ]
