# Generated by Django 2.2.4 on 2022-06-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_belt', '0002_remove_job_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
