# Generated by Django 2.2.4 on 2022-06-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='granted',
            name='like',
            field=models.ManyToManyField(related_name='grant_wish', to='wish_app.User'),
        ),
    ]
