# Generated by Django 2.2 on 2020-06-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='grant_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wish',
            name='grant_wish',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='wish',
            name='liked_by',
            field=models.ManyToManyField(related_name='has_liked', to='belt_app.User'),
        ),
    ]
