# Generated by Django 2.2.4 on 2022-06-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SemiRestfulTVShowsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
